### ISSUE TITLE
Optionally run command before serving static files

### ISSUE THREAD

**Issue by otherjoel** [samdphillips/raco-static-web#9]
I’m wondering if you would be interested in a PR that allows running an arbitrary command (or perhaps a `dynamic-require`d function) before serving a static file, including in scenarios where the requested file doesn’t exist at the time of the request. 

My immediate goal is to have a static web server that can also automatically rebuild HTML pages (or other assets) when their dependencies change. So a request for `page.html` would cause the server to first blindly run, say, `make page.html` which would rebuild that file if needed (even if it doesn’t yet exist), or be a no-op if it's already up to date (or not given as a target in the makefile).

I would probably go about this by adding an option that would hook into or replace the custom `url->path` function at line 196, but maybe there is a better approach.

https://github.com/samdphillips/raco-static-web/blob/595c2272d55181ca14b17c5827140b900dc78f9e/main.rkt#L196-L197

**Comment by samdphillips** [comment]
Sounds good.  Which interface do you think would be better (shell command or function)?

**Comment by otherjoel** [comment]
Still thinking about that. My main thought is that it should be easy to specify via the command line, since `raco-static-web` is primarily a command-line tool. I’m leaning toward a shell command for simplicity.

**Comment by otherjoel** [comment]
I'm leaning towards `raco static-web --make-target-command "make ~a"`. It would check the string to ensure exactly 0 or 1 uses of `"~a"`; if found, it would use `(system (format command-str target-path))`.

This is poor from a security perspective, but since this package is intended as an analogue of [Python’s http.server](https://docs.python.org/3/library/http.server.html), I assume the same warnings about not using in production apply anyway.

**Comment by samdphillips** [comment]
I was leaning towards setting an environment variable when the command is called.  Then `command-str` (or the script/makefile/etc. invoked) can just use that and the program would not need to parse the `command-str`.

Your example would then be:
```
raco static-web --make-target-command "make $TARGET_FILE"
```

And the `system` call would be (ugh this is longer than I hoped...):
```
(parameterize ([current-environment (environment-variable-copy (current-environment))])
  (putenv "TARGET_FILE" target-path)
  (system command-str))
```

**Comment by otherjoel** [comment]
I found another way to meet the need: spawn [fswatch][1] in the background to run `make` whenever a source file changes. ([Example script][2]).

This might be a better solution for a couple reasons. It rebuilds targets as soon as they get stale, rather than waiting until the targets are requested. And it doesn’t open any holes in the server itself for what might be a narrow use case.

If you concur, I’m inclined to close this issue.

[1]: https://github.com/emcrisostomo/fswatch
[2]: https://joeldueck.com/code/jdcom/file?ci=10edd8c32e90ae08&name=start-server&ln=12-14

**Comment by samdphillips** [comment]
There are probably other good use cases for this, but unless there is an immediate need, let's leave it.
